compressionLevel: mixed

enableGlobalCache: false

nodeLinker: node-modules

npmRegistryServer: "https://registry.npmjs.org"

packageExtensions:
  "@blueprintjs/core@*":
    dependencies:
      react-dom: "*"
  "@blueprintjs/select@*":
    dependencies:
      react-dom: "*"

pnpMode: loose

yarnPath: .yarn/releases/yarn-4.4.1.cjs
